### ISSUE TITLE
How to use bulk RNASeq data?

### ISSUE THREAD

**Issue by akiss-me** [saeyslab/multinichenetr#37]
Hi, thank you for the brilliant tool! I have 8 bulk RNASeq samples (4 control, 4 treated). Can I use multinichenet to analyze it?

**Comment by browaeysrobin** [comment]
Hi @akiss-me 

In case you have bulk RNA-seq of sorted cell populations, yes.
You can use the same pipeline and ideas, but instead of the pseudobulk DE and expression, you can use your bulk expression. You will have to change the corresponding functions yourself, though, since we are not going to support/maintain this.
