### ISSUE TITLE
no sample_id

### ISSUE THREAD

**Issue by GGboy-Zzz** [saeyslab/multinichenetr#41]
hi,can i define "sample_id" = NA or others, so ignore this parameter？

**Comment by browaeysrobin** [comment]
Hi @GGboy-Zzz 

This is not possible since MultiNicheNet is a method explicitly taking into account sample-to-sample variability.

**Comment by GGboy-Zzz** [comment]
I browsed all [vignettes] in nichenetr, and I cant find a methods to infer cell-cell interactions from multiple receiver. My data is about embryonic development, there are significant differences in cell types at different stages, can you give me some suggestions about  how to  perform nichenetr?

**Comment by browaeysrobin** [comment]
Hi @GGboy-Zzz 

Short answer: NicheNet is a receiver cell type - focused pipeline. You should thus run a NicheNet analysis for one receiver at the time. Once you have set up your analysis pipeline for one receiver, you can of course write a wrapper so the analysis happens for all cell types of interest in your data. 

For further questions concerning nichenetr, you should open a github issue there and not here since this is here multinichenetr.

**Comment by GGboy-Zzz** [comment]
Okay, thank you very much
