### ISSUE TITLE
get_abundance_expression_info Slot Extraction is Unclear

### ISSUE THREAD

**Issue by DarioS** [saeyslab/multinichenetr#65]
`get_abundance_expression_info` doesn't clearly state which SCE slot the abundances are gotten from. Can it be user-customised?

**Comment by browaeysrobin** [comment]
Hi @DarioS 

Are you referring to the abundances (cell numbers) or expression data? 

I don't think I fully understand how the abundances could be retrieved from different SCE slots. What we do now is just: `SummarizedExperiment::colData(sce)[,c(sample_id, group_id, celltype_id)]` counting the nr of cells per celltype/sample combination.

**Comment by DarioS** [comment]
I was thinking about gene abundance (i.e. sequencing reads per gene symbol).

> Calculate the average and fraction of expression of each gene per sample and per group.

In the list of assays, there could be raw counts, log-counts and batch-corrected values present. Can a user choose one?

**Comment by browaeysrobin** [comment]
Hi @DarioS 

The raw counts are used. With multinichenetr, pseudobulk expression values are calculated by aggregating raw counts. These pseudobulk values are then directly used in the DE analysis and normalized (and if requested also batch-corrected with combat-seq) to get normalized Pseudobulk expression values that are used to define cell-type specificity and calculate ligand-receptor expression products for visualizations. 

Since all these operations start from the raw-counts-aggregated pseudobulk data, we don't recommend using other starting assays.
