### ISSUE TITLE
Cell types abundances in prioritisation score

### ISSUE THREAD

**Issue by EspressoKris** [saeyslab/multinichenetr#75]
Thanks for the fantastic tool!

I have a question regarding the prioritisation score. Does this take into consideration cell type abundances, as in cellular fractions? The point is that even interactions that are not differentially expressed may be increasingly physiologically relevant when a sender is X times more propagated.

If not, I was wondering if there is anyway to take cell type abundances computed from differential abundances tools (i.e. MILO estimated log fold changes) into consideration?

Also, on a different note, is there anyway to make a simple cell type to cell type interaction chord plot as in cellphoneDB? How do we define the total number of relevant interactions per group?

Thanks!

**Comment by browaeysrobin** [comment]
Hi @EspressoKris 

The implemented prioritization function does not consider cell type abundances. Once cell types are present, they will be considered in the analysis. Interactions involving more abundant cell types will not be weighted more. 

If you think this is relevant for your data, you can consider scoring interactions by the relative abundance of the sender and receiver cell type, and incorporating that in the final prioritization score. You can see how you can customize the prioritization yourself in this vignette: https://github.com/saeyslab/multinichenetr/blob/main/vignettes/add_proteomics_MISC.knit.md

You can always make a celltype-celltype interaction plot yourself by considering the top _n_ interactions and counting the LR pairs between the cell types for those _n_ LR pairs. The best value of _n_ will depend on the nr of cell types in your analysis (don't take this too low). We don't provide code ourselves to do this, because we MultiNicheNet was designed to rank interactions according to presumed functional relevance (to help downstream experimental validation), not to give all possible interactions between cell types. The total nr. of interactions between cell types may be biased towards cell types producing "promiscuous" ligands/receptors (like ECM factors) and this is not necessarily informative.
