### ISSUE TITLE
Process killed (out of memory)

### ISSUE THREAD

**Issue by TessaGillett** [saeyslab/multinichenetr#88]
Hi,

First of all, thank you for developing this package. Hope you can help me with the following: when calling multi_nichenet_analysis() my process keeps getting killed due to memory problems. I'm running MultiNicheNet (v2) on a dataset containing about 240K cells, 46 donors, on a desktop with 64 GB RAM. (Also, currently testing it on a subset of 4000 genes to get things working, but I'll want to perform the real analysis on my full 36K set of genes.) 

I'm wondering whether I'm doing something wrong, or whether I should just scale up to a system with more memory. Especially because previously we've managed to run MNN v1 on a similar dataset without much trouble. Any ideas?

Thanks!
Tessa

**Comment by browaeysrobin** [comment]
Hi @TessaGillett 

To help identifying the issue / proposing a solution, we strongly recommend you run the analysis step-by-step (https://github.com/saeyslab/multinichenetr/blob/main/vignettes/basic_analysis_steps_MISC.knit.md).
(gene and cell type filtering are explicitly performed there as steps)

Then we can localize the specific step where MultiNicheNet runs out of memory.

**Comment by TessaGillett** [comment]
Hi Robin,

Thanks for the reply, that did help find the problem. The crash happens when running the ligand activity prediction - I'm thinking we've probably got too many cell type labels involved in this analysis, 37 after filtering. Any guesses on what amount of memory I'd need for that to work out?

**Comment by browaeysrobin** [comment]
Hi @TessaGillett 

You probably ran the analysis with multiple cores? In that case, it is possible that the ligand activity analysis will run out of memory. I suggest using only one core for such a big dataset. Running this step will take a long time, but should not run out of memory with one core.

Other note: 37 cell types is a lot. It is possible to run MNN for so many cell types, but interpreting the output will be hard given the large number of cell type pairs you will end up with (the top50 interactions overall will only cover a very very small fraction of all relevant interactions). Maybe it will make more sense to aggregate some cell types, or to focus on a couple of cell types of interest for the downstream interpretation.

**Comment by TessaGillett** [comment]
Perfect, I'm giving that a go now, thanks for the suggestion! I'll report back when it's done.

(As for the number of cell types: I'm mostly interested in a few specific cell types. I'll mainly be looking at their interactions with the other cell types in my dataset like you suggest, so I'm hoping it will be okay.)

**Comment by TessaGillett** [comment]
Hi Robin,

My ligand activity prediction is running smoothly, but unfortunately I'm now running into the same memory issue when generating the prioritization tables. Any more suggestions on how to solve that? Thanks again for your help! 

Also, one more question: in v1 of MNN we were allowed to set our own weights for the different prioritization criteria, but in the v2 vignettes I don't see that option anymore - is there any way to still do this?

**Comment by browaeysrobin** [comment]
Hi @TessaGillett 

You can remove some intermediate objects that you don't need anymore after the ligand activity step, such as `frq_list` and `sce`. If you remove these, I expect you will have sufficient memory left to run the prioritization. It is possible that the step in https://github.com/saeyslab/multinichenetr/blob/main/vignettes/basic_analysis_steps_MISC.knit.md#calculate-the-across-samples-expression-correlation-between-ligand-receptor-pairs-and-target-genes will require too much memory, but that step is optional and not required for the basic analysis. 

About the prioritization weights: we shifted to a system where users can choose different biological scenarios that accord to specified weights instead of tweaking weights themselves. This choice was made to avoid that users can keep tweaking results to get the output they wanted without good prior reason. You can check the currently available scenarios in the documentation of the prioritization function. If you have a reason/biological setting that is currently not covered, you can open a github issue, and we will consider adding that option.

**Comment by browaeysrobin** [comment]
Hi @TessaGillett, any update on whether this fixed your issue?

**Comment by TessaGillett** [comment]
Hi Robin, thanks for the follow up. Between this and a slight downsizing of our annotations I did manage to fix the problem.

As for the prioritization weight scenarios: we don't have a specific new biological scenario that we're dealing with, but we would like to be able to compare the MNN output with and without inclusion of the score for ligand activity, as we're a little worried about the bias that might be introduced by that sort of prior knowledge (in general, but especially blind spots in cell type specificity of interaction effects).

**Comment by browaeysrobin** [comment]
Hi @TessaGillett 

In the latest version you can choose the scenario: `scenario = "no_activity"` in the `generate_prioritization_tables` function. This will do exactly as you say.
